#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/bin/autoexec
#------------------------------------------------------------------------------
# Project Name      - Extra/source/autoexec/autoexec
# Started On        - Thu 31 Oct 22:49:41 GMT 2019
# Last Change       - Sun 27 Jun 20:52:40 BST 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Features:
#
#TODO: Add timing functionality to C FILEs.
#TODO: Consider support for Node.js.
#
# Bugs:
#
#TODO: When using `-e`|`--exec`, flags for it are included as a single word.
#
#      This isn't so much of a bug as an intentional oversight. I'd like to
#      address this eventually, but it's not a priority, right now.
#
#TODO: Using AutoExec for man pages (pagers) is buggy, but functional.
#
#      More specifically, the prompt shows through and when ^C-ing, the last
#      line (message line with exit status) still shows. Pretty ugly. I'm not
#      sure this is something which can be fixed, as it's probably just a
#      limitation of Shell/terminals.
#
# Optional Dependencies:
#
#   gcc (>= 4:7.4.0-1)
#
# Dependencies:
#
#   bash (>= 4.4.18-2)
#   coreutils (>= 8.28-1)
#   file (>= 1:5.32-2)
#   ncurses-bin (>= 6.1-1)
#------------------------------------------------------------------------------

CurVer='2021-06-27'
Progrm=${0##*/}
ProgrmFancy='AutoExec'

Usage(){
	while read; do
		printf '%s\n' "$REPLY"
	done <<-EOF
		Usage: $Progrm [OPTS] [FILE] [FILE_ARGS]

		  -h, --help               - Displays this help information.
		  -v, --version            - Output only the version datestamp.
		  -C, --no-color           - Disable ANSI color escape sequences.
		  -E, --no-exit            - Omit the exit status on the bottom-right.
		  -S, --no-spinner         - Omit 'spinner' from the waiting message.
		  -W, --no-waitmsg         - Omit the waiting message at the end.
		  -c, --check              - Check for errors before executing.
		  -e, --exec <NAME>        - Use NAME as the interpreter or program.
		  -f, --force              - Forces use of that which is unsupported.
		  -o, --once               - Execute FILE only once; no looping.
		  -r, --refresh <INT>      - Adjust to fit your performance needs.
		  -t, --time               - Time the execution of FILE.

		  To exit $ProgrmFancy, send the SIGINT (130) signal using the Ctrl + C
		  shortcut (^C). Your previous terminal layout will be restored.

		  When forcing, unsupported mimetypes and executables will be allowed.
	EOF
}

Err(){
	printf 'ERROR: %s\n' "$2" 1>&2
	[ $1 -eq 1 ] && exit 1
}

TIMEFORMAT='[R:%3R|U:%3U|S:%3S|P:%P]'
MainDir="$HOME/.config/autoexec"
Config="$MainDir/config"

Check=False
Color=True
ExitStatus=True
Force=False
Refresh=0.05
Spinner=True
Time=False
WaitMSG=True

# `OR_*` are override flags.
while [ "$1" ]; do
	case $1 in
		--)
			break ;;
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf "%s\n" "$CurVer"; exit 0 ;;
		--exec|-e)
			shift

			if [ -z "$1" ]; then
				Err 1 'Name of command not provided.'
			elif ! type -P "$1" > /dev/null 2>&1; then
				Err 1 'Provided command not found in PATH.'
			else
				Exec=$1
			fi ;;
		--refresh|-r)
			shift

			if [ -z "$1" ]; then
				Err 1 'Unspecified refresh rate.'
			elif ! [[ $1 =~ ^([[:digit:]]+|[[:digit:]]+.[[:digit:]]+)$ ]]; then
				Err 1 'Invalid refresh rate.'
			else
				OR_Refresh='True'
				Refresh=$1
			fi ;;
		--once|-o)
			OR_Once='True'
			Once='True' ;;
		--no-waitmsg|-W)
			OR_WaitMSG='True'
			WaitMSG='False' ;;
		--no-spinner|-S)
			OR_Spinner='True'
			Spinner='False' ;;
		--no-exit|-E)
			OR_ExitStatus='True'
			ExitStatus='False' ;;
		--no-color|-C)
			OR_Color='True'
			Color='False' ;;
		--force|-f)
			OR_Force='True'
			Force='True' ;;
		--time|-t)
			OR_Time='True'
			Time='True' ;;
		--check|-c)
			OR_Check='True'
			Check='True' ;;
		-*)
			Err 1 'Incorrect option(s) specified.' ;;
		*)
			break ;;
	esac
	shift
done

if [ "$Once" == 'True' -a ${#Refresh} -gt 0 ]; then
	Err 1 "Options '--once|-o' and '--refresh|-r' aren't compatible."
fi

[ -z "$1" ] && Err 1 'Missing argument -- file name required.'
[ -f "$1" ] || Err 1 'Provided file is not a file.'
[ -r "$1" ] || Err 1 'Provided file is unreadable.'

ExecFile=$1; shift

DepChk(){
	DepCount=0
	for Dep in "$@"; {
		if ! type -P "$Dep" &> /dev/null; then
			Err 0 "Dependency '$Dep' not met."
			let DepCount++
		fi
	}

	[ $DepCount -gt 0 ] && exit 1
}

DepChk file tput sleep stat

#-------------------------------------------------Handle the Configuration File

[ -d "$MainDir" ] || mkdir -p "$MainDir"

if [ -f "$Config" ]; then
	[ -r "$Config" ] || Err 1 'Configuration file unreadable.'

	InvalidKeys=0

	# Usage: Boolean <KEY> <VALUE>
	Boolean() {
		case $2 in
			True|False)
				return 0 ;;
			'')
				Err 0 "Key '$1' missing boolean." ;;
			*)
				Err 0 "Key '$1' invalid boolean." ;;
		esac

		let InvalidSets++
	}

	InvalidSets=0
	while read; do
		case $REPLY in
			'#'*|'') continue ;;
		esac

		IFS='=' read Key Value <<< "$REPLY"

		case $Key in
			Color)
				[ "$OR_Color" == 'True' ] && continue
				Boolean "$Key" "$Value" && Color=$Value ;;
			ExitStatus)
				[ "$OR_ExitStatus" == 'True' ] && continue
				Boolean "$Key" "$Value" && ExitStatus=$Value ;;
			Spinner)
				[ "$OR_Spinner" == 'True' ] && continue
				Boolean "$Key" "$Value" && Spinner=$Value ;;
			WaitMSG)
				[ "$OR_WaitMSG" == 'True' ] && continue
				Boolean "$Key" "$Value" && WaitMSG=$Value ;;
			Check)
				[ "$OR_Check" == 'True' ] && continue
				Boolean "$Key" "$Value" && Check=$Value ;;
			Force)
				[ "$OR_Force" == 'True' ] && continue
				Boolean "$Key" "$Value" && Force=$Value ;;
			Refresh)
				[ "$OR_Refresh" == 'True' ] && continue

				REGEX='^([[:digit:]]+|[[:digit:]]+\.[[:digit:]]+)$'
				if [[ $Value =~ $REGEX ]]; then
					Refresh=$Value
				else
					Err 0 "Key '$Key' given invalid refresh rate."
				fi ;;
			Time)
				[ "$OR_Time" == 'True' ] && continue
				Boolean "$Key" "$Value" && Time=$Value ;;
			*)
				Err 0 "Key '$Key' invalid."
				let InvalidSets++ ;;
		esac
	done < "$Config"

	[ $InvalidSets -gt 0 ] && exit 1
else
	while read; do
		printf '%s\n' "$REPLY"
	done <<-EOF > "$Config"
		# User configuration generated by $ProgrmFancy ($CurVer). For
		# information on these options, please refer to the autoexec(1)
		# manual page or its usage output.

		Check=False
		Color=True
		ExitStatus=True
		Force=False
		Refresh=0.05
		Spinner=True
		Time=False
		WaitMSG=True
	EOF
fi

#----------------------------------------------Prepare for an Execute Main Loop

if [ "$Force" == 'False' ]; then
	case $Exec in
		*/man|man|*/less|less|*/pager|pager|*/more|more)
			Err 1 "Using pagers with $ProgrmFancy is unsupported." ;;
	esac

	case `file -b --mime-type "$ExecFile"` in
		application|application/*)
			Err 1 "Binary files are not supported." ;;
	esac
fi

case $ExecFile in
	*.c|*.cpp)
		if [ "$Time" == 'True' ]; then
			Err 1 "Option '--time|-t' not supported on FILE."
		fi

		CFound='True' ;;
esac

TRAP(){
	if [ "$Once" != 'True' ]; then
		tput ed
		tput rmcup
	fi

	# Needs to be here otherwise the above line clears it.
	if [ "$Force" == 'False' ]; then
		if [ "$UnsupportedCheck" == 'True' ]; then
			Err 1 "Option '--check|-c' not supported on FILE."
		elif  [ "$TimingErr" == 'True' ]; then
			Err 1 'Timing of C programs not yet supported.'
		fi
	fi

	exit 0
}

trap 'TRAP' SIGINT EXIT

[ "$Once" == 'True' ] || tput smcup

if [ "$Once" != 'True' ]; then
	WinchHandler(){
		tput clear
		Lines=`tput lines`
		Columns=`tput cols`
	}

	trap 'WinchHandler' WINCH

	WinchHandler
fi

while :; do
	# Determine the interpreter to use.
	if [ "$CFound" != 'True' ] && [ -z "$Exec" ]; then
		if [ -z "$1" ]; then
			read Line < "$ExecFile"
		else
			Line=$1
		fi

		ExecStr=${Line#\#!}
		ExecPath=${Command%%* }
		ExecBase=${ExecPath##*/}
	fi

	if [ -f "$ExecFile" ] && [ -r "$ExecFile" ]; then
		SSE=`stat -c '%Y' "$ExecFile" 2> /dev/null`

		if [ 0${SSEOld//[![:digit:]]} -lt 0${SSE//[![:digit:]]} ]; then
			[ "$Once" == 'True' ] || tput clear

			# If using DASH or BASH, check for errors before executing.
			if [ "$Check" == 'True' ]; then
				unset Errors
				if [ "$ExecBase" == 'bash' ]; then
					$ExecStr -n "$ExecFile" || Errors='True'
				elif [ "$ExecBase" == 'sh' ]; then
					File=`type -P sh`
					Link=`readlink -e "$File"`
					if [ "$Link" == '/bin/dash' ]; then
						/bin/dash -n "$ExecFile" || Errors='True'
					else
						UnsupportedCheck='True'
					fi
				else
					UnsupportedCheck='True'
				fi

				[ "$Force" == 'False' -a "$UnsupportedCheck" == 'True' ] && exit 1
			fi

			if [ "$Errors" != 'True' ]; then
				if [ "$CFound" == 'True' ]; then
					if [ "$Time" == 'True' ]; then
						OutFile='/tmp/ae_cfile_run.tmp'
						if gcc -o "$OutFile" "$ExecFile"; then
							chmod 755 "$OutFile"
							"$OutFile" "$@"
							Exit=$?
						else
							Exit=999
						fi
					else
						TimingErr='True'
						exit 1
					fi
				else
					if [ "$Time" == 'True' ]; then
						time $ExecStr "$ExecFile" "$@"
						Exit=$?
					else
						$ExecStr "$ExecFile" "$@"
						Exit=$?
					fi
				fi

			else
				Exit=999
			fi
		fi

		SSEOld=${SSE//[![:digit:]]}
	else
		if [ "$Once" != 'True' ]; then
			tput ed; tput rmcup
		fi

		Err 1 'File not found or inaccessible.'
	fi

	if [ "$Once" != 'True' ]; then
		# Have the exit status on the bottom-right of the terminal.
		if [ "$ExitStatus" == 'True' ]; then
			tput cup $Lines $((Columns - 3))

			if [ "$Color" == 'True' ]; then
				if [ $Exit -eq 0 ]; then
					printf '\e[2;37m%#3d\e[0m' $Exit
				else
					printf '\e[1;31m%#3d\e[0m' $Exit
				fi
			else
				printf '%#3d' $Exit
			fi
		fi

		if [ "$WaitMSG" == 'True' ]; then
			if [ "$Spinner" == 'True' ]; then
				for Char in '|' '/' '-' '\'; {
					tput cud $Lines

					if [ "$Color" == 'True' ]; then
						printf '\r\e[2;37m[%s] Waiting for changes...\e[0m ' "$Char"
					else
						printf '\r[%s] Waiting for changes... ' "$Char"
					fi

					sleep 0.04
				}
			else
				tput cud $Lines

				if [ "$Color" == 'True' ]; then
					printf '\r\e[2;37mWaiting for changes...\e[0m '
				else
					printf '\rWaiting for changes... '
				fi
			fi
		fi
	fi

	[ "$Once" == 'True' ] && exit 0

	sleep $Refresh
done
